import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val appcompat: String = "1.1.0"

  const val constraintlayout: String = "2.0.0-beta2"

  const val core_ktx: String = "1.2.0-alpha04"

  const val androidx_databinding: String = "3.6.0-alpha10"

  const val lifecycle_extensions: String = "2.2.0-alpha04"

  const val lifecycle_viewmodel_savedstate: String = "1.0.0-alpha04"

  const val androidx_navigation: String = "2.2.0-alpha02"

  const val androidx_room: String = "2.2.0-rc01"

  const val espresso_core: String = "3.3.0-alpha02"

  const val androidx_test_runner: String = "1.3.0-alpha02"

  const val viewpager2: String = "1.0.0-beta04"

  const val lottie: String = "3.0.7"

  const val aapt2: String = "3.6.0-alpha10-5720371"

  const val com_android_tools_build_gradle: String = "3.6.0-alpha10"

  const val lint_gradle: String = "26.6.0-alpha10"

  const val com_github_bumptech_glide: String = "4.9.0"

  const val material: String = "1.1.0-alpha10"

  const val gson: String = "2.8.5"

  const val timber: String = "4.7.1"

  const val logging_interceptor: String = "4.1.1"

  const val converter_gson: String = "2.6.1"

  const val retrofit: String = "2.6.1"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val junit: String = "4.13-beta-3"

  const val library: String = "1.3.2"

  const val anko_commons: String = "0.10.8"

  const val org_jetbrains_kotlin: String = "1.3.50"

  const val org_koin: String = "2.0.1"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.2"

  const val gradleCurrentVersion: String = "5.5"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
